### ISSUE TITLE
Edição de Projeto

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2175]
**Não implementaremos componente de atividade** neste momento.

Topo:

- [x] breadcrumb: #2047

- [x] entity-profile e entity-cover: #2049

- [x] entity-social-media: #2048

- [ ] entity-fields: #2078

- [x] entity-links: #2059 e #2036

Corpo:

- [x] starts_on e ends_on: #2172

- [x] select-entity: #2037

- [ ] entity-fields: #2078

- [x] entity-file-lists: #2106

- [x] entity-links: #2059 e #2036

- [x] entity-gallery-video: #2058

- [x] entity-gallery (image uploader): #2057

Barra de Ações:

- [x] entity-action: #2033

Barra lateral direita:

- [x] entity-admins: #2050

- [x] mc-tag-list: #2170 e #2171

- [x] entity-related-agents: #2051

- [x] entity-owner: #2038

- [ ] entity-revisions:	#2052 Somente na V2
	
Avisos:

- [x] #2079

- [x] messages: #2076	

Frame:

- [x] #2093
