### ISSUE TITLE
Visualização do Agente Individual

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2190]
Topo:

- [x] breadcrumb:	#2047

- [x] entity-profile e entity-cover:	#2049

- [x] entity-social-media:	#2048

- [x] entity-field:	#2078

- [x] entity-links:	#2017

Corpo:

- [x] tabs:	#2165 (ref #1885)

- [x] map:	#2056

- [x] entity-field:	#2078

- [x] entity-file-lists:	#2106

- [x] entity-links:	#2017

- [x] entity-gallery-video:	#2058

- [x] entity-gallery (image uploader):	#2023	

- [ ] entity-request-ownership:	#2160

Barra de Ações:

- [x] entity-action:	#2033

Lateral Direita:

- [x] mc-tag-list:	#2171

- [x] entity-social-media:	#2048

- [x] entity-seals:	#2018

- [x] mc-tag-list:	#2170 e #2171	

- [x] entity-admins:	#2167

- [x] entity-related-agents:	#2051

- [x] share-links:	#1987

- [x] entity-ownerships:	#2166

Frame:

- [x] #2156
