### ISSUE TITLE
Edição de Agente Coletivo

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/mapasculturais#2191]
Topo:

- [x] breadcrumb	#2047

- [x] entity-profile e entity-cover:	#2049

- [x] entity-social-media:	#2048

- [ ] entity-field:	#2078

- [x] entity-links:	#2059 e #2036

Corpo:

- [ ] entity-field:	#2078

- [x] entity-location: #2055

- [x] map:	#2056

- [x] entity-file-lists:	#2106	

- [x] entity-links:	#2059 e #2036

- [x] entity-gallery-video:	#2058

- [x] entity-gallery (image uploader):	#2057

Barra de Ação:

- [x] entity-action:	#2033

Barra Lateral Direita:

- [x] mc-tag-list:	#2171

- [x] entity-social-media:	#2048

- [x] entity-admins:	#2167

- [x] mc-tag-list:	#2170 e #2171

- [x] entity-related-agents:	#2051

- [x] entity-owner:	#2038

- [ ] entity-revisions:	#2052

Avisos:

- [x] messages:	#2076

- [x] #2079	

Frame:

- [x] #2108
